dydxprotocol/v4-abacus

build.gradle.kts, integration/iOS/Pods/Pods.xcodeproj/project.pbxproj, src/commonMain/kotlin/exchange.dydx.abacus/output/Market.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/assets/AssetProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/assets/AssetsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/modal/TradingStateMachine.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/V3AppStateTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/V4AppStateMachineForegroundCycleTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/MarketsChannelMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/ValidationsMock.kt, v4_abacus.podspec
Two fixes
1. Occasionally, if socket v4_markets data comes in before market configuration json, the assets configurations are messed up because baseAsset is no longer used (either missing, or ""). So now we always split the first element of the "ticker" as asset.
2. Filter out markets which didn't have market configuration (missing "name" field). This will filter out "TEST-USD", and also filter out future markets which we didn't prepare the configurations for.
=> TRCL-2662 baseAsset is no longer in the payload

src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/LaunchIncentivePointProcessor.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/LaunchIncentiveMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tickets/TRCL3551Tests.kt
[MOB-288 : investigate trading rewards not showing](https://linear.app/dydx/issue/MOB-288/investigate-trading-rewards-not-showing)
issue was that we were expecting ints for the chaos labs API payload values from API
```
/query/api/dydx/points/<address>?n=3
```
-> 
```
{
"incentivePoints": 0.982044,
"marketMakingIncentivePoints": 0.009789599999999999,
"dydxRewards": 0
}
```
change was to parse values as doubles
now tests are passing with the double mock values
=> MOB-288 : investigate trading rewards not showing

build.gradle.kts, src/androidMain/kotlin/exchange.dydx.abacus/state/manager/SystemUtils.android.kt, src/jvmMain/kotlin/exchange/dydx/abacus/state/manager/SystemUtils.kt
A bit of pre-req work to replacing Napier with our own multiplatform logger.
In addition to some general build.gradle.kts cleanup, this PR mainly:
- Removes iosX64 target (trivial to add this back later if needed)
- Removes androidMain sourceset and Android Gradle Plugin dependencies. We're a pure JVM library, so shouldn't need Android knowledge. (Also, jvmMain was configured to depend on androidMain, which is opposite of convention)
=> Cleanup sourcesets.

build.gradle.kts, gradle.properties, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, v4_abacus.podspec
- didn't realize we have the `subscribeToCandles` field in V1, we should also skip calling the candles API on indexer config / market set for web
- add back the two properties that were previously removed -- i think that is related to build performance
- fixed yarn lock file, which prev. throws an error when building for js
=> skip retreive market candles based on appconfigs

build.gradle.kts
This allows viewing of Kotlin sources in browser dev tools.
=> Embed Kotlin sources into JavaScript sourcemaps.

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/validator/TriggerOrdersInputValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/validation/TriggerOrdersInputValidationTests.kt, v4_abacus.podspec
Pulling in new translations from [here](https://github.com/dydxprotocol/v4-localization/commit/d122db5c52db9164036380efc717b5e6dce7714c).
Updated existing tests, and built locally  in FE to verify.
=> 1.6.34: Update SL/TP trigger/limit price errors to be SL/TP specific

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TriggerOrdersInputTests.kt, v4_abacus.podspec
my bad; synced with Se - percentage calculation should be independent of size of order. 
Formula is:
`percentageDiff = (leverage * abs(entryPrice - triggerPrice) / notionalTotal) * 100`
also:
- Updated to clear (set to null) other price inputs when one is set to null
- Also fixed bug where leverage is negative on short positions (and I didn't notice)
Tested on frontend - this time it looks correct 🙃 
https://github.com/dydxprotocol/v4-abacus/assets/70078372/9a64fabc-8f8f-4de0-82ea-e12eaec45ddb
=> v1.6.37: Fix sltp percentage calculation

build.gradle.kts, integration/iOS/Pods/Pods.xcodeproj/project.pbxproj, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/TriggerOrdersInputValidator.kt, v4_abacus.podspec
triple equals "===" do not work for iOS string comparisons after compilation. Replacing all triple equals string comparisons with double equals in this PR.
=> replace === with ==

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/V4TransactionTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt, v4_abacus.podspec
This is the last time I'll fix percentage calculations; worked with Se for an afternoon and we finally feel confident on it. Missing part to the calculation was that:
- We were using the fixed notionalTotal rather than the scaled notionalTotal (scaled to user order size)
- We were missing (order) size in several calculations
None of the tests had to be updated because `size` of ETH in our tests is just 1, go figure (this is mocked out in the channels data, I don't feel super strongly about mocking some new data to test a non-1 size, but can if others feel strongly; reasoning: I don't think this calculation should change anymore/be reused anywhere else).
Also fixed double callback being returned in `commitTriggerOrders`: `send` is called from both `submitCancelOrder` and …
=> v1.6.40: Fix percentage calculations, fix double payload return on commitTriggerOrders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/AnalyticsUtils.kt, v4_abacus.podspec
- for cancel events, add more details from order
- for place order click, infer time in force based on [v4-clients](https://github.com/dydxprotocol/v4-clients/blob/305c0761979a4f75afff213707a50c2552c14ef5/v4-client-js/src/clients/helpers/chain-helpers.ts#L43) helper function, since payload's original time in force can be null
=> analytics: add missing fields in place/cancel order events

build.gradle.kts, v4_abacus.podspec
oops realized in https://github.com/dydxprotocol/v4-abacus/pull/309, I did not actually properly bump the version (https://github.com/dydxprotocol/v4-abacus/pull/306 was also 1.6.43). Tested out in testnet and looks like you don't get the updates in web until version is properly bumped :(
=> fix abacus version

src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeTriggerPriceValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TradeInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TriggerOrdersInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/validation/TradeRequiredInputTests.kt
As per [product](https://linear.app/dydx/issue/CT-779/remove-warning-for-users-placing-stop-market-orders), update stop market slippages from:
- Major markets: 0.05 -> 0.1
- Non-major markets: 0.1 -> 0.2
For cleanliness, updated constants to be shared between `TriggerOrdersInputCalculator` and `TradeInputCalculator`; removed unused `MARKET_ORDER_SLIPPAGE_WARNING_THRESHOLD`.
Also remove `STOP_MARKET_ORDER_MAY_NOT_EXECUTE ` warning prompting users to use stop limit orders.
=> Update stop market order liquidity warning + params

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt, v4_abacus.podspec
related: [DSGN-707 : enable env.json feature flag isSltpEnabled](https://linear.app/dydx/issue/DSGN-707/enable-envjson-feature-flag-issltpenabled)
exposes isSlTpLimitOrdersEnabled feature flag for enabling sl/tp from env.json
=> add isSlTpLimitOrdersEnabled feature flag

detekt-baseline.xml, detekt.yml
For the declaration `exchange.dydx.abacus.state.Foo`, Detekt expects the following folder structure:
```
/exchange
/dydx
/abacus
/state
Foo.kt
```
but instead we have:
```
/exchange.dydx.abacus
/state
Foo.kt
```
Could fix this by restructuring folders, but don't think it's super worthwhile and may cause some thrash in PRs, so just turning the rule off instead.
Regenerated the baseline as well.
=> Turn off InvalidPackageDeclaration Detekt rule

build.gradle.kts, v4_abacus.podspec
bump for https://github.com/dydxprotocol/v4-abacus/pull/325 because v is now outdated rip
=> Bump abacus version

integration/iOS/Podfile
sister pr to https://github.com/dydxprotocol/v4-web/pull/495
converting to building via relative path. this allows devs to have their abacus and web repos wherever they want as long as they are in the same dir, which keeps us in line with what we claim in our readme
=> chore: use relative path

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/app/helper/TriggerOrderToastGenerator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/helper/TriggerOrderToastGeneratorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/V4TransactionTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt, v4_abacus.podspec
context: comment here: https://github.com/dydxprotocol/v4-web/pull/496#discussion_r1589768792
[Update](https://github.com/dydxprotocol/v4-abacus/pull/341/files#diff-11a8cac3e8953445d9f31efa06c9797a6fa600812b158940ccd407f839c7feeeL80) abacus to return `kollections.List` instead of `kotlin.collections.List` so that the web code can use `toArray()` (instead of some janky conversion).
- Involved updating `listOf` to `iListOf` 
- Cleaned up some `?.` checks
- built locally on FE and confirmed everything works 👍 
- unsure how to test on mobile / if edits need to be made
=> chore(sltp): update HumanReadableTriggerOrdersPayload [place/cancel]OrderPayloads list return type

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/squid/SquidProcessor.kt, v4_abacus.podspec
Sorted in abacus so both mobile + web get this change. 
Seemed like `SquidProcessor` was the most logical place to do this - but also open to better ideas 🤔 
Pulled and built locally into web and verified that asset options are alphabetical
=> v1.7.6: sort squid asset + chain list alphabetically

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionStats.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionsSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkHelper.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/AnalyticsUtils.kt, v4_abacus.podspec
=> add validator url / network tracking in analytics

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, v4_abacus.podspec
- better tracking of round trip time (e.g. a short term order being filled vs. just indexed)
- also useful for other future tracking (how often is an order filled during the same FE session)
tested locally:
=> [analytics] track order status changes

build.gradle.kts, bump_version.sh, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, v4_abacus.podspec
Latest Kotlin MM tooling added a step that causes issue with our iOS build workflow.  Updating the bump_version script to remove the step.
Also removing duplicated declaration of HistoricalPnlPeriod (it's also in Settings.kt)
=> Fix ios podspec

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/V4ForegroundCycleTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4ForegroundCycleTests.kt, v4_abacus.podspec
`createdAtOrAfter` -> `createdOnOrAfter`; it was never correctly applied :(
180 -> 90 days since that's the max we show on FE portfolio anyways; if there are requests for an all-time situation we'll come back, but currently that'll reduce api calls for longer time traders
=> Fix historical pnl param + update pnl retrieval to max 90 days

.github/workflows/bump_version.yml, .github/workflows/ci.yml, bump_version_gh_action.sh
The last part of the version number will be automatically incremented after your PR lands.  After this lands, no more manual bump_version.sh will be needed unless you want to update the major/minor version.
Tested on my private repo.
=> Add Github Action to automatically bump version at PR merge

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/Compliance.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/TestFactory.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/V4RestrictionsTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4RestrictionsTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt, v4_abacus.podspec
linear: [MOB-514 : add expires at to abacus](https://linear.app/dydx/issue/MOB-514/add-expires-at-to-abacus)
- adds the `expiresAt` value to the `Compliance` object which is 7 days advanced from `updatedAt`
- adds tests for v1 and v2 abacus to test calculation of `expiresAt`
- cleans up some logic for setting compliance object
=> MOB-514 : add `expiresAt` at to abacus

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/Account.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt, v4_abacus.podspec
- Update the `Environment` type in abacus with `rewardsHistoryStartDateMs` from [here](https://github.com/dydxprotocol/v4-web/pull/578/files#diff-8817bf86fd45bfdf9c54b3c3c52f6e944fb4a05bc7d9f3b9cfd448fc8932130eR299)
- Remove hardcoded `180 days` from query for trading rewards, and instead calculate based on `now - startDateMs + 2.days` (for buffer). Default to 180 days from start if for some reason env.json isn't configured to have this
- Fix previous placeholder
- Built locally, verified that data is fetched all the way to start date, tested with a non-null and null env.json variable
=> update trading rewards to fetch all rewards since rewards_history_start_date defined in env.json

src/commonMain/kotlin/exchange.dydx.abacus/output/Account.kt, src/commonTest/kotlin/exchange.dydx.abacus/TradingRewardsTests.kt
found a bug while building locally where it seemed like cumulative chart was not strictly increasing; realized it's because we were not updating `cumulativeTotal` when merging existing historical rewards with new data correctly. Updated test to account for that
=> fix(tradingRewardHistory): fix cumulative rewards calculation

src/commonMain/kotlin/exchange.dydx.abacus/di/AbacusComponent.kt, src/iosArm64Main/kotlin/di/AbacusComponent.ios.kt, src/iosSimulatorArm64Main/kotlin/di/AbacusComponent.ios.kt, src/jsMain/kotlin/exchange.dydx.abacus/di/AbacusComponent.js.kt, src/jvmMain/kotlin/di/AbacusComponent.jvm.kt
need to create expect/actual for kotlin-inject component creation methods for every final platform. (See kotlin-inject KMP examples.)
https://github.com/evant/kotlin-inject-samples/blob/main/multiplatform/echo/src/macosArm64Main/kotlin/App.macosArm64.kt
=> Fix publishToMavenLocal

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/Configs.kt, v4_abacus.podspec
need to render an equity tier table in FE similar to this, with tier 1..6
we're also removing equity tier limit validation on the FE, which will be done in another PR. therefore ignoring any duplicated processing logic here
=> Add equity tiers in configs output

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/Configs.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/TriggerOrdersInputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeInputDataValidator.kt, v4_abacus.podspec
removing FE validation for equity tier to opt for showing protocol error (broadcast error) instead, so we can just use their way of counting number of orders as source of truth
=> Remove equity tier validation

build.gradle.kts, docs/Input/TransferInput.md, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TransferInput.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TransferInputTests.kt
- filled out `TransferInput.md` a bit more (it's outdated)
- add `memo` to `TransferInput`; clear it when transfer type switches (but maintain it between token type switches)
- I considered adding a `needsMemo` field to the different transfer type options (`WithdrawalInputOptions`, etc) but that seemed like overkill when the caller can just conditionally render the memo field depending on type - and maybe we'd want to allow users to fill in a memo in other cases in the future?
Tested with tests; built locally
https://github.com/dydxprotocol/v4-abacus/assets/70078372/73acda34-c595-46ef-8e9e-db4702d20b7a
=> create memo field for transferInput

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/base/MergeWithIds.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/TradesProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/FillsProcessor.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v3/V3PerpTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4DuplicateWebsocketMessageTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/TradesChannelMock.kt
We're seeing quite a few crashes from trying to render fills and trades with duplicate IDs. After discussing with James, it sounds like it is to be expected that duplicate messages are received over the websocket. 
The main issue here is that for Processors that return a List of items, we are just appending items blindly. To limit the scope of this PR, we won't change the API signature from List to Map, but rather will use a set to ensure that only a single item with the same ID is returned.
Note: `mutableSetOf()` is backed by a `LinkedHashSet`, so ordering is preserved.
This PR addresses the two main offenders: Fills and Trades. There are other processors that have the same potential pitfall, but I will tackle these in a follow-up.
=> De-dupe fills and trades from WebSocket.

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRoutePayloadProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipRouteMock.kt
implements skip replacement for squid /route endpoint
This PR implements the skip analog of squid's /route endpoint by utilizing Skip's msgs_direct endpoint.
In order to do this we:
- Implemented the receivedRoute method on the SkipProcessor
- Implemented the receivedRouteV2 method on the SkipProcessor
- Created and implemented the `SkipRouteProcesor
- Created and implemented the SkipRoutePayloadProcessor
- Skip does not provide all the same data that Squid does, so we did our best to keep the data format as similar as possible. We'll have to make some updates on the web side to handle these changes though. Most notably:
- gasLimit should no longer be required
Some things to cleanup after this PR:
- errors property is set in a pretty hacky way to coerce the skip payload to mimic squid's. …
=> feat: skip route + msgs endpoints [OTE-348]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginModeCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt
Should only care about open orders.  When position is closed, there is a FILLED order that needs to be skipped.
=> TRA-321 Reset needsMarginMode after position is closed

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/responses/ParsingError.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/app/adaptors/V4TransactionErrors.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkHelper.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, v4_abacus.podspec
- broadcast errors from different module/codespace have different meanings; adding codespace to localized stringkey to differentiate
- use order payload instead of transfer in the place order / isolated margin flow, so that client has access to order client Id when there's an error
=> isolated margin: use correct payload + codespace broadcast errors

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, v4_abacus.podspec
Two fixes:
- Reference groupedSubaccounts for TriggerOrdersInputCalculator.
- Use child subaccount number when constructing payload.
=> Use appropriate subaccount for SL/TP triggers.

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, v4_abacus.podspec
testing on web, there's a bug where if dydx wallet isn't immediately connected (i.e. either need to recover keys / reconnect wallet), user fees won't be fetched and no trading rewards/fees will show up in place order CTA
this is because we fetch user fee tiers and stats on account's `didSetValidatorConnected`, and only when a subaccount is already fetched. however in most cases, `subaccounts.values.any { it.realized }` will be false when validator is first set to connected
fix is we will also try to fetch those things on `subscribeToSubaccount`, and checking that it's the first subaccount that gets "realized", keeping similar logic
=> fix: retrieve user fees on subaccount set

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginModeCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt
* `AccountTransformer`
* remove `calculateIsolatedMarginTransferAmount`. Moved calculation for transfer amount into `MarginModeCalculator`
* Utilize new `getShouldTransferCollateral` and `calculateIsolatedMarginTranasferAmount` 
* `MarginModeCalculator`
*  Add 4 new helper functions
* `getIsIncreasingPositionSize` which is used in `getShouldTransferCollateral`
* `calculateIsolatedMarginTransferAmount` which caps the targetLeverage to 98% of Max Leverage and returns `getTransferAmountFromTargetLeverage`
* `TradeInputCalculator`
* Update `ISOLATED` switch cases to return correct values
* utilize `getShouldTransferCollateral` to determine whether to `calculateIsolatedMarginTransferAmount`
* Save value to `summary.isolatedMarginTransferAmount`
* `TradeInput`
* add …
=> v1.7.75: Add buffer and use oraclePrice to determine collateral movement

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/AnalyticsUtils.kt
- add logic to cancel trigger orders when its associated position has been closed or flipped
- tested locally and works on both cross and isolated positions' orphaned trigger orders
An order will be canceled if it meets the following conditions:
- order is a conditional order, reduce-only
- order is untriggered or open status
- order's market has no position or position was flipped (i.e. different direction than the order's side)
followup:
- currently cancel reason will say user canceled it, not ideal but there'll be extra logic needed to override indexer's cancel reason and we want to ship this asap
- tests :)
=> Automatically cancel trigger orders if position has been closed/flipped

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt
- Update Order Enum string comparisons.
- Changes from lowerCase to capitalized will now be handled by using `enu.name`
=> v1.7.83: Update order status enum strings

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt
We should use "==" instead of "===" to compare strings.  In Kotlin, "===" compares the object address, so it would return false if the two strings are allocated separately even though their content is the same.  In general, we should always use "==" unless there is a reason not to.
Also moving the callback to the last param of the cancelOrder function, since it's generally the desired pattern.
=> Fix an issue where SL/TP gets canceled

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRoutePayloadProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Map+Utils.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/String+Utils.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipRouteMock.kt
Followup to https://github.com/dydxprotocol/v4-abacus/pull/417
withdrawals weren't fully enabled due to additional flows we hadn't accounted for.
also fixes some small bugs and cleans up some unused comments, suppressions, etc.
Performed QA on several flows e2e with this PR.
QA'd Flows:
- Cctp deposit 
- Cctp withdrawal
- Cctp auto sweep
TODO QA:
- Non cctp deposit
- Non cctp withdrawal
- Non cctp auto sweep
- Exchange deposit
- Exchange withdrawal
=> feat: top level withdrawal methods [OTE-389] [2/n]

src/commonMain/kotlin/exchange.dydx.abacus/processor/router/IRouterProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt
NOTE: This doesn't fully enable testnet. We cannot perform withdrawals and deposits. But this is still past parity with existing squid integration as the route endpoint always fails on testnets. 
Squid integration: fails on `/v1/route`. `Withdraw` / `Deposit` button is never enabled, fees never estimated, just get a route error.
Skip Integration (this PR): succeeds on `/msgs_direct`, button is enabled, fees estimated. Failure upon clicking the button.
=> feat: enable testnet OTE flows

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt
Web utilizes the 24h sparklines, re-enable for AbacusV2 configs for web.
=> change retrieveSparklines to true for web

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TradeInput.kt
Otherwise, when the first market to trade is isolated (i.e., initiateTrade() gets called), the targetLeverage of the position is not applied.
=> Apply the same logic to calculate marginMode and targetLeverage for new and existing trade

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/ParentSubaccountsChannelMock.kt
in calculating how much margin to transfer, should take absolute net size change instead of using the full order amount, so when the position is flipped, it doesn't transfer too much margin
=> update margin transfer calculation with absolute net size (flipped isolated position)

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+AdjustIsolatedMarginInput.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/AdjustIsolatedMarginInputTests.kt
Mobile app sends the input field as-is, so there can be negative numbers.  For margin, we will just ignore the sign.
=> Fix negative input to margin input amount

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/IRouterProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/squid/SquidProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, v4_abacus.podspec
Exposes get chain by id helper method. This allows us to get the `chainName` that the frontend wants to display. This is also probably just useful in general. 
This poses the question - should we continue being 'react'y and storing all react related data into the state? Or do we want to expose data that react can't update directly via abacus.
=> feat: expose get chain by id method

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountTransformer.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/OrderbookChannelMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/ParentSubaccountsChannelMock.kt
when inputting a trade (or close position) that reduces an isolated position, and there is no other open orders, postorder cross free collateral should increase, and position margin for the existing isolated position should decrease
main changes:
- introduces the concept of how much collateral can be transferred out (which we'll later incorporate to transfer out collateral on subaccount/ positions change); this will allow cross free collateral to reflect post transfer amount
- fixes usdcSize (which can be the transfer amount) being overwritten in `transformDelta` by passing in extra param `hasTransfer` that skips that
=> Isolated markets: reduce position delta

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, v4_abacus.podspec
+ refactoring
+ calculate transfer payload for isolated trade on placing order
+ close position should get a more efficient way to find the child subaccount number (can assume it's the first subaccount with that open market position)
=> isolated [2/n]: calculate transfer payload for isolated trade on the fly

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, v4_abacus.podspec
calculate how much to transfer with position size difference inferred from trade input instead of position, since delta has not been applied to position
this should fix receipt being slow / weird state where it was using an outdated position size
alternative route of applying transfer after position delta is duplicating even more code so didn't go down that path
https://github.com/dydxprotocol/v4-abacus/assets/9400120/3d31023b-1ac3-4e48-81e9-6f0393f7ae83
=> isolated [1/n]: update position size difference calculation / fix slow receipt

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountTransformer.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, v4_abacus.podspec
1. fix logic to determine when to transfer out margin (previously flipped position + reduce only logic was wrong)
2. when transferring out, estimate collateral that will be transferred out as quote balance + size*price
3. position margin receipt: overwrite usdcSize as 0 in trade delta so that post order position margin is null
=> isolated: fix margin diff for closing position / transfer out

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, v4_abacus.podspec
wooof. 
we were originally assuming that the transfer.token/chain values were the correct values to calculate decimals.
this isn't true because for deposits that represents the 'from' values instead of the 'to' values, which provides an incorrect amount out value.
after solving that we then needed to account for the fact that we save the SDK approved denom for native tokens (Ex00EE0E whatever that's not right but you know what i mean), but skip gives us {chain-name}-native. so when finding a token by id when retrieving a route, we need to make sure we're searching for both the denom and skip denom.
=> fix: correct decimal calcs

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionStats.kt, v4_abacus.podspec
part of an attempt to reduce indexer trailing statuses triggering
other things that will be added
- make toast go away on the FE when status goes back to normal
- listen to visibility change (i.e. background vs foreground) and reconnect statemanager
=> chore: relax indexer trailing threshold

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, v4_abacus.podspec
Turning on smart relay to prep for strangelove divorce. once we no longer depend on grant funds to subsidize user fees, we will want to use skip's smart relay feature for CCTP withdrawals.
this unfortunately will make some withdrawals quite a bit more pricy. we are going to add copy around that to help users understand the increased fees, which we believe is a more user friendly solution than the current solution of having skip throw errors if the fees are too high (hence, we are setting allow_unsafe to true)
=> fix: use smart relay and allow unsafe with cctp withdraws

build.gradle.kts, json_add_attr.sh, src/commonMain/kotlin/indexer/codegen/IndexerAPIOrderStatus.kt, swagger_codegen.sh, v4_abacus.podspec
The codegen tool doesn't support union type such as 
`export type APIOrderStatus = OrderStatus | BestEffortOpenedStatus`
So we will have to hack it to make it work for `APIOrderStatus` (the only union type so far).
=> Codegen for IndexerAPIOrderStatus

build.gradle.kts, detekt.yml, src/commonMain/kotlin/exchange.dydx.abacus/output/Account.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/base/MergeWithIds.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/WalletProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/AccountProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/FillProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/FillsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/SubaccountProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/PerpTradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Wallet.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/ParsingHelper.kt, src/commonTest/kotlin/exchange.dydx.abacus/localizer/MockLocalizer.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/wallet/account/FillProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/wallet/account/FillsProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/extensions/TradingStateMachine+Markets.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/mock/LocalizerProtocolMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/mock/processor/wallet/account/FillProcessorMock.kt, v4_abacus.podspec
Constructing subaccount fills with static typed data and codegen models from Indexer.  This can serve as a reference for future migration.
- Feature-flagged via `staticTyping` from Abacus config and retaining all existing behavior with the data map.   
- New processor functions have names starting with "process".
- Previous data map-based functions are renamed with trailing "Deprecated".  
- Tested with Android.
=>  Static typing for subaccount fills

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, v4_abacus.podspec
remove `break`s in `parseOrdersToMatchPlaceOrdersAndCancelOrders` which caused a local order placement that's canceled to skip cancel confirmation logging
tested locally
don't see why there needs to be a `break`
=> fix: cancel order logging - fix skipping it because of unnecessary break

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TradeInput.kt, v4_abacus.podspec
exposes ability for caller to manually update the last edited input (necessary for https://github.com/dydxprotocol/v4-web/pull/790) which requires manually implicitly updating the last edited input on toggle (since we are no longer showing both usdc + asset inputs in one view)
=> chore: expose setter for last edited input (size)

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRoutePayloadProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/CctpWithdrawState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipRouteMock.kt, v4_abacus.podspec
fixes smart relay by adding multi message support.
only cctp smart relays are multi msg objects right now. we support this by:
- adding `allMessages` to abacus' state
- format all messages, not just the first one, in the `SkipRoutePayloadProcessor` and set it to the `allMessages` state property
- refactor `payload` to `singleMessagePayload` in the `cctpWithdrawState`
- add `multiMessagePayload` to `cctpWithdrawState`
- based on whether a `cctpWithdrawState` has `multi` or `single` message payload, use `CctpMultiMsgWithdraw` or `CctpWithdraw`
this PR also:
- bumps minimum uusdc needed in noble wallet to 20000 (~.02USDC) due to increases fees now that foundation is no longer subsidizing CCTP relays
- restricts cctp withdrawals to cctp and ibc bridges. this prevents the routing algorithm …
=> fix: smart relay w/ multi msg support [OTE-563]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, v4_abacus.podspec
we can't handle multi-txs. this was erroneously enabled in an attempt to allow smart-relay, but that doesn't use multi tx.
if a user attempts to withdraw via skip for Base or Polygon their funds will just get sent to noble and then autoswept back.
disallowing multi-tx's prevent users from withdrawing to Base or Polgyon at all until we've fully cut over and are ready to release them as CCTP transfers
=> fix: disallow multi-tx

README.md, build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TriggerOrdersInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt, v4_abacus.podspec
per request of product: 
```
BTC/ETH/SOL from 10% -> 5%
All others from 20% -> 10%
*note SOL is now being included in the BTC/ETH category
````
=> chore: update conditional order slippage, promote solana to major market

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, v4_abacus.podspec
context: https://dydx-team.slack.com/archives/C0738MMRX9C/p1721247027232859
Edge case found for small axelar transfers - non osmosis/neutron swap venues can become preferred (in this case, terra). to remediate this (since we don't have a fallback address for terra) we're restricting swap venues for non-cctp withdrawals and deposits.
=> chore: add swap venues

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, v4_abacus.podspec
we don't want to autosweep subaccount funds back to 0 if it's not a child subaccount of parent 0
i.e. we won't sweep if:
1. subaccount is a parent subaccount (i.e. < 128; since 2 % 128 = 2)
2. subaccount is a child of other parent subaccounts. (e.g. subaccount 129) assuming we can just leave it alone since FE only cares about subaccount 0 as parent right now, and subaccount 129 will only be added via API and API users can just deal with the sweep back logic themselves
we also don't want to pick empty subaccounts that are a parent subaccount (or not related to subaccount 0) as isolated trade candidates
=> fix: only autosweep subaccount funds back to 0 if it's a child subaccount of parent 0 + don't pick it as isolated trade subaccount candidate

src/commonMain/kotlin/exchange.dydx.abacus/state/app/adaptors/V4TransactionErrors.kt, v4_abacus.podspec
while most tx errors are broadcast errors with codespace + code, sometimes there can be errors from simulation/query that are not properly formatted / missing those info. to get around it, i'm adding string matching to parse the error message to see if it starts with "Query failed", and then do additional string matching
in particular, add support for better subaccount update failed result handling, so we can show an error such as 
instead of 
- this also needs slight updating on FE/web to make sure we're sending in the Error's error message to abacus (https://github.com/dydxprotocol/v4-web/pull/823)
=> transaction error handling: parse query result error for subaccount update

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeMarketOrderInputValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/validation/TradeMarketOrderTests.kt, v4_abacus.podspec
1. update orderbook slippage calculation to use mid market price
2. update slippage warning/errors logic*
3. update slippage error to show "place limit order" action string
*show slippage warning/error when:
- min(oracle slippage, orderbook slippage) > 5%/10%
- if missing oracle slippage, but orderbook slippage is >5%/10%
if orderbook slippage is missing (i.e. no mid price), that should be caught by liquidity validation
=> slippage: update slippage logic + add back index slippage validations

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessor.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, v4_abacus.podspec
Save skip's `warning` property in their `msgs_direct` response to state.
This will allow us to warn users if their proposed route will consume an inordinate amount of their funds due to transfer fees
=> feat: expose skip warnings [OTE-621]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Network.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionsSupervisor.kt, v4_abacus.podspec
Currently, the estimated block height for short time orders is calculated by the lapse of the block time (from the server) and the local system time.  This won't work if the system clock is wrong (i.e., running behind), and user will get an order submission failure.
We now add a `localTime` that records the local system time when updating `BlockAndTime`, and use it for the calculation.  Since for the purpose of calculating time lapse the "first block time" and "last block time" are now both in local system time, the calculation logic works even when the system clock is inaccurate.
=> Calculate height by comparing local system time

src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRoutePayloadProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipChainsMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipRouteMock.kt
Adds SVM support to skip API calls and the skip route processor.
Chains and assets returned by skip are filtered by the apps, so Solana chains and assets should appear hidden until filters on the apps are modified to include them.
=> feat: Add svm support to skip processor 

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipChainsMock.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipTokensMock.kt, v4_abacus.podspec
what this PR does:
- filter out non EVM and non SVM chains (we had a typo that was preventing this before, lol)
- **THIS PR NO LONGER DOES THIS** prefer Arb as default chain (Ethereum has very high fees)
- NOTE: this means that arb is the default chains for withdrawals **and deposits** since the skip processor doesn't have access to the current transfer type. we can differentiate the 2 but it's an extra lift which may be non-trivial
- sorts native asset as the first item after usdc asset if applicable
what this PR does not:
- do anything to CCTP USDC asset ordering. USDC assets on CCTP are already sorted to the top in web so we aren't changing abacus behavior here.
- do anything to Non-CCTP USDC asset ordering. If desired, we can move USDC assets on non CCTP chains to the top, but for now …
=> feat: improved onboarding ux [OTE-509]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, v4_abacus.podspec
https://linear.app/dydx/issue/OTE-669/hide-usdt-assets-from-onboarding-modal
This PR filters out tokens if their symbol contains `USDT` 
This is a temporary measure until the [IBC USDT rate limits](https://ibc.range.org/ibc/rate-limits) reset on saturday.
=> feat: hide usdt assets [OTE-669]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, v4_abacus.podspec
Autosweep min of 20000 is not enough for gas fees. It's possible to get a failed IBC due to gas fees but the code keeps retrying over and over, leading to a noisy dev console/network tab
Whats happening here?
- Abacus performs autosweeping for users
What is autosweeping?
- Autosweeping is the act of periodically (every 10 seconds as of today) IBC transferring funds from the user's noble wallet to their dydx wallet
=> fix: bump autosweep min to 50000 [OTE-673]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, v4_abacus.podspec
fix: we were passing in merged subaccount equity which caused significantly incorrect leverage calculations when a user had non trivial margin in isolated positions.
after the fix, it's still not _great_. Our calculation for `position.leverage.post` still doesn't exactly match with our leverage calculations for market trade because:
- the market trade calculation goes through the orderbook and gives a best estimate based on available market prices and order sizes (rather than looking only at oracle price like `position.leverage.post`)
- the market trade calculation also takes into consideration feeRate which `position.leverage.post` does not
in other words, the receipt summary at the bottom of the trade form assumes that account equity does not change with a proposed trade (because it's …
=> fix: fix incorrect size calculation on leverage trade size inputs for cross margin orders

src/commonMain/kotlin/exchange.dydx.abacus/processor/router/IRouterProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/squid/SquidProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalTransferInputState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Squid.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipVenuesMock.kt
enables evm swaps by:
- calling the swap venues endpoint and storing the uniswap venues internally in the class. i opted to keep the list as a class variable instead of throwing it into state for the following reasons:
- it doesn't need to be updated 
- it doesn't need to be exposed to the clients
- considering the previous two, feels like a whole lot of boilerplate/overhead for no material gain
- it should only be referenced specifically for calling skip endpoints and not be available to parts of the code that do not directly work skip endpoints
- when @ruixhuang 's work to migrate everything to `internalState` is done, we can really easily move it into that state.
- adding the `swap_venues` list to the nonCCTP deposit payload (this enables the request to to include evm swap venues)
- …
=> feat: evm swaps for deposits [OTE-700]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountCalculatorV2.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4AccountTests.kt, v4_abacus.podspec
update unrealized pnl percent calculation to match SLTP: multiple percent by scaled leverage
"currently the p&l on positions table doesnt factor the leverage you're using. if you're 10x levered and ETH moves 10%, your P&L should be 100% not 10%. (SL/TP already accounts for leverage)"
=> chore: update unrealized pnl percent to be based on leverage

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TradeInput.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4ClosePositionTests.kt, v4_abacus.podspec
we were previously setting this manually in web, but we can just move this into abacus
i have an upcoming PR that adds limit close functionality, which will also default to set mid market price as limit price around the same place
=> Default close position input to use full close (percent input as 1)

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, v4_abacus.podspec
Backend endpoint PR: https://github.com/dydxprotocol/v4-chain/pull/2117
=> feat: call compliance endpoint for keplr

src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
adds logs to all the onboarding flow API calls, for both the request and response bodies.
This should give us a lot more insight into any strangeness that might occur with the onboarding flow
This is a POC - ideally we'll either use DD RUM or add logging to the network helper methods so we get logging automatically.
=> abacus datadog poc [OTE-719][2/n]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Logger.kt, v4_abacus.podspec
This PR:
- updates Logger.kt's `e` function to accept a context (IMap so its json serializable), and error (i'm using Kotlin's default Error which is probably the wrong type, still investigating this one)
- adds `ddInfo` to Logger.kt. This behaves similarly to `Logger.d` except that it ships logs to datadog and accepts a context IMap
=> chore: datadog poc [OTE-719][1/n]

.github/workflows/bump_version_on_main.yml, build.gradle.kts, v4_abacus.podspec
I've given @mobile-build-bot permission to bypass `main` branch protection.
TODO:
Once this merges, need to add a commit message filter on the `publish` workflow in Bitrise to only run on commits that start with `BUMP-VERSION`
=> Test new bump version workflow

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/AdjustIsolatedMarginInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/AdjustIsolatedMarginInputTests.kt, v4_abacus.podspec
tested locally and found that 100% almost always fails 🫠 . Leaving behind 0.01 seems to almost always work, but this const can be easily adjusted. Basically only applies if we hit the 100% toggle button.
=> fix(isolatedMargin): update isolated margin addition of margin to leave behind buffer for collateralization checks

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeMarketOrderInputValidator.kt, v4_abacus.podspec
it depends on summary.slippage. but summary can be a non-null empty object.
=> fix showing one sided liquidity error when it should not

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/TradeInputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeOrderInputValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt, v4_abacus.podspec
Add validation for isolated margin limit orders so that traders can't place orders <$20 total equity.
Renamed `TradeMarketOrderInputValidator` -> `TradeOrderInputValidator`
- Added `const isolatedLimitOrderMinimumEquity = 20`
- Added logic for validating that isolated margin limit orders (and stop limit and take profit limit) are using at least 20 dollars of equity by comparing post freeCollateral with current freeCollateral
- Wrote 2 versions (one is statically typed, one isn't)
- Error: `ISOLATED_MARGIN_LIMIT_ORDER_BELOW_MINIMUM` - https://github.com/dydxprotocol/v4-localization/pull/670
Added tests in `V4TradeInputTests`
I don't think our FE is reading in the link stuff rn, but willl dig in more. Here is proof of concept of it working: …
=> chore: add min validation for isolated limit orders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/PerpTradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionStats.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionTracker.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/TradeValidationTracker.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/InputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/TradeInputValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/fakes/FakeTrackingProtocol.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/state/model/TradingStateMachineTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/validation/TradeMarketOrderTests.kt, v4_abacus.podspec
- Cleans up AnalyticsEvent a bit, the `rawValue` is not needed. We can just use the enum name directly.
- Adds a new class `TradeValidationTracker` which logs validation results and does some quick and dirty de-duping, since the validators are run quite often.
- Wires up TradeValidationTracker in TradeInputValidator and pipes through needed dependencies.
context: https://dydx-team.slack.com/archives/C06EMK1746T/p1722891345373099
=> feat: Add tracking for TradeInputValidator.

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/Vault.kt, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultAccount.kt, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultDepositWithdrawForm.kt, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultIndexerModels.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultAccountTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultTests.kt, v4_abacus.podspec
=> fix: use IList in all js types

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionPayloadProvider.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/AnalyticsUtils.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AccountsChannelMock.kt, v4_abacus.podspec
add functionality to cancel all orders (either in all markets or a single market)
(originally wanted to use batch cancel for short term orders, but integration was a bit more complicated (due to needing tx broadcast mode to get success/failed order ids, and canceling short term orders via FE almost always fails). therefore will reconsider when batch cancel also support stateful orders.
-> decided to just rely on TX queue to submit cancels one by one. short term cancels don't need txcommit so they will go first. we could potentially run into rate limiting issue here but decided that it'll be rare for retail users.)
testing:
- unit test
- tested locally on web
=> add cancel orders with tx queue

build.gradle.kts, trigger_v4web_reload.sh, v4_abacus.podspec
Add v4WebHotSwapTrigger task which copies development build JS directly into v4-web's node_modules.
This enables fully integrated continuous builds from v4-web: make a change in abacus and it will trigger compilation and fast path "installation" of the library into v4-web and trigger a Vite restart.
Can manually run via `./gradlew v4WebHotSwapTrigger --continuous` (will update `install-local-abacus` on the v4-web side).
=> Add v4WebHotSwap Gradle Tasks

src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginModeCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputMarginModeCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/Market.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/ClosePositionInputProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TradeInputProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TradeInput.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt
context https://github.com/dydxprotocol/v4-abacus/pull/613
=> chore: update default target leverage on isolated market orders to be max market leverage

src/commonMain/kotlin/exchange.dydx.abacus/calculator/ReceiptCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountTransformerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TransferInputCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/Input.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TransferInputProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/squid/SquidProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalTransferInputState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/TransferInputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/transfer/TransferFieldsValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/transfer/TransferOutValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/transfer/WithdrawalCapacityValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/transfer/WithdrawalGatingValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TransferInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4SquidTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4WithdrawalSafetyChecksTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/validation/TransferRequiredInputTests.kt
- Updating Transfer Input for static typing. The Squid/Skip payload is still parsed as map, and can be converted in the future if we have time.
- Updating Withdrawal gating for static typing.
- Updating all remaining tests. You can now set staticTyping = true in BaseTests to test the new codepath.
- Tested on Android
=> TRCL-3643 Static Typing: TransferInput

src/commonMain/kotlin/exchange.dydx.abacus/output/Market.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketsSummaryProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Sparklines.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/MarketsSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4ForegroundCycleTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/markets/MarketProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/markets/MarketsProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/mock/processor/markets/MarketProcessorMock.kt
Fetching 7 day sparkline to determine if the market is new for mobile apps.  Web already does this outside Abacus, and it's currently configured to fetch for mobile apps only.  But we can remove the web code and use the isNew field from Abacus in the future.
Also updating the 1 day sparkline fetch interval from 1 minute to 1 hour per Slack discussion.
=> TRCL-3682 Add isNew to PerpetualMarket

docs/Input/TradeInput.md, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/AdjustIsolatedMarginInputCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputMarketOrderCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputOptionsCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/ClosePositionInputProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TradeInputField+Actions.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TradeInputProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt
Adds a `balancePercent` to trade size inputs such that user can choose an amount for their trade based on the percentage of their available balance (we're replacing the 1x...10x leverage buttons with this percentage toggle). See screen recording proof of concept:
https://github.com/user-attachments/assets/c8562fa9-508d-435c-bd59-53cc64398f9b
For now, this only applies to cross market orders. Will follow up in separate PR to enable for isolated market orders (will probably choose to use a `needsPercentBalance` field). Will likely not enable for limit orders until leverage slider is added. 
Note this change is non breaking: to get this, caller just has to update to call into this new field (and set appropriately).
=> add new balancePercent input to trade size inputs

docs/Input/TradeInput.md, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputOptionsCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/TradeInputOptionsTests.kt
adds a `needsBalancePercent` to `TradeInput` which tells caller whether we should render toggles. For now, only enabling for cross market orders because isolated margin has a slight rounding bug + calculations need to be updated to take into account `targetLeverage`
see below for proof of concept:
https://github.com/user-attachments/assets/133a53a9-ae46-42f5-8004-00de121f2409
=> enable balancePercent field on (cross) market orders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/input/ValidationError.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/BaseInputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeOrderInputValidator.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4WithdrawalSafetyChecksTests.kt, v4_abacus.podspec
Created the enum `ErrorFormat` instead of just having a bunch of strings for `ErrorParam.format`
- Added a new option: `UsdcPrice` instead of just having `Price`
- Reason here is that web currently parses this as formatting the price val to market `tickSize` decimals, but for some cases (like the isolated margin error), we know it's usdc and should always be formatted to 2 decimal places
- Passing through type `UsdcPrice` allows web to switch case on it and use `2` decimal places instead of looking at `tickSize`
I dug around for a long time in `BaseInputValidator.kt` to see if I could just have abacus format it properly and not have the web format it [here](https://github.com/dydxprotocol/v4-web/blob/main/src/lib/tradeData.ts#L70) but got absolutely lost and couldn't quite untangle how …
=> chore: add usdcSize type to ErrorFormat

src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
This should get rid of the vast majority of our route errors with the name `proto: (line X:X): invalid value for string type: null`
This was occurring due to the fact that some nully string values were being accepted in the abacus code before attempting to fire an API request. Until we have datadog it'll be a bit challenging to trace them down, but this should clear most if not all of them
=> fix: empty route addresses [OTE-769]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionsSupervisor.kt, v4_abacus.podspec
Fix a problem with last PR.  The indexer url is needed when calling getOptimalNode, so we need to set it without an async callback.
=> Set the indexer URL without callback

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionPayloadProvider.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt, v4_abacus.podspec
adding a helper function to market close all open positions under parent subaccount 0
in the future when indexer supports mid price ws endpoint, and protocol support limit close (reduce-only non-IOC), we'll only add a limit close option. until then, this is just full closing all positions with market price (i.e. oracle price + slippage)
tested locally https://github.com/dydxprotocol/v4-web/pull/1031
=> feat: market close all positions

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputMarketOrderCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, v4_abacus.podspec
noticed a bug when testing this feature - isolated margin percent inputs looked wrong esp when the amount was high - realized it was cuz the collateral transfer calculation was wrong - we need to include the isolatedPnlImpact in the balance used
(for some reason when I build locally now it keeps telling the testnet chain is halted? I tried with building a local abacus with no change but an extra space and it still said halted so assuming this is not related)
https://github.com/user-attachments/assets/5323f9e2-7ea5-4347-aa78-045ab320cc28
=> fix: fix isolated pnl transfer calc

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt, v4_abacus.podspec
return payloads for orders / close positions status tracking
=> close all positions: return payload

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkHelper.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountTransactionTracker.kt, v4_abacus.podspec
research found out that these fields are missing
think we didn't add them back when refactoring to the different supervisors?
=> Add api state params to tracking

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultDepositWithdrawForm.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt, v4_abacus.podspec
Reverts dydxprotocol/v4-abacus#676
=> Revert "fix: vaults submission types match better"

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultAccount.kt, src/commonMain/kotlin/indexer/codegen/IndexerTransferType.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultAccountTests.kt, swagger_codegen.sh, v4_abacus.podspec
The enum value has to be the same as the string value for the serialization to work correctly.  Unfortunately, the current codegen utility doesn't do that, so we have to perform extra post-processing.
=> Fix codegen with TransferType

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/TransferInputCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TransferInputCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TransferInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalTransferInputState.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, v4_abacus.podspec
add estimatedRouteDurationSeconds to route + summary state so we can display it in the UI
pretty sure this is a breaking change since we're updating the name of the state attribute. IMO worth doing to make the property more descriptive
=> feat: add eta to state [OTE-832]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultAccount.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultAccountTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt, v4_abacus.podspec
Frontends will have to calculate the predicted time: NOW + (unlock block height - latest block height) * 1s
=> Vault share unlocks metadata

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultAccount.kt, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultDepositWithdrawForm.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonMain/kotlin/indexer/models/chain/OnChainAccountVaultResponse.kt, src/commonMain/kotlin/indexer/models/chain/OnChainVaultDepositWithdrawSlippageResponse.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultAccountTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt, v4_abacus.podspec
Currently all the validator response data models are stored at package indexer.models.chain, so it's better to move the new ones there to be consistent....
=> Rename validator data models for Vaults and move them to the correct package

src/commonMain/kotlin/exchange.dydx.abacus/validator/AccountInputValidator.kt
we weren't getting the deposit button on web with 0 equity - traced it back to an incorrect check for child subaccount (i.e. correct way is [here](https://github.com/dydxprotocol/v4-abacus/blob/main/src/commonMain/kotlin/exchange.dydx.abacus/validator/InputValidator.kt#L108))
verified by building locally
=> fix: fix trade form not showing deposit button when no equity

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/Vault.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4VaultTests.kt, v4_abacus.podspec
Should be 30d return but extrapolated to 1 year
=> fix: correct vault apr calculation

src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionsSupervisor.kt
revert core logic of https://github.com/dydxprotocol/v4-abacus/pull/661 
PR 661 optimistically assigned a node and then attempted to connect to the optimalnode in the background. This was intended to reduce latency to find an optimal validator.
However, defaulting to the first node occasionally results in a connection failure. v4-web doesn't have the ability to properly reconnect once a connection attempt has failed which has cause a significant degradation in user experience in a significant number of cases
=> fix: revert default validator url logic

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/input/TradeInput.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeAccountStateValidator.kt, v4_abacus.podspec
overly strict FE validation for self-trade is preventing users from placing stop orders
we already have protocol code in place for preventing self-trade (canceling maker orders); therefore we can relax this validation and just let the sl/tp orders be placed, since most likely the open limit orders will be filled before the sltp orders are triggered
testing:
before:
after:
also tested that this validation still exists for other order types (limit)
=> fix: remove self trade validation for sltp orders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountCalculatorV2.kt, v4_abacus.podspec
Position calculation needs oracle price for the market.  During initial app loads, the oracle prices might come after the subaccount data.  In this case, we will want to delay the subaccount calculation until the oracle prices arrive.  Otherwise, the app would display incorrect portfolio values.
Tested it on Android.
Before:
[old1.webm](https://github.com/user-attachments/assets/4f049c80-c2c6-4d73-805a-ca25784f1358)
After:
[newl1.webm](https://github.com/user-attachments/assets/bf7116d1-a4a4-4a38-a96a-ca52ac082ba5)
=> Wait for the position values before calculating subaccount

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/assets/AssetProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/assets/AssetsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/PerpTradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Markets.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SystemSupervisor.kt, src/commonMain/kotlin/indexer/models/configs/ConfigsMarketAssetResponse.kt
Add new AssetMetadataProcessor and AppConfig flag
=> chore(metadata-service): Fetch Asset information from MetadataService

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultDepositWithdrawForm.kt, src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt, v4_abacus.podspec
I forgot null vault account is expected on user's first deposit. Shame shame shame
=> fix: dust fix introduced bug when account isn't provided

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, v4_abacus.podspec
Ability to toggle autosweep so FE can temporarily disable it while performing multi tx withdrawals. This way the frontend wont be dependent on abacus' polling logic
=> feat: toggle autosweep [OTE-866]

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/app/adaptors/V4TransactionErrors.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/NetworkHelper.kt, v4_abacus.podspec
when a tx failed because of the 'out of gas' result, it isn't treated as an error when it should
'out of gas' happens when our gas estimation is somehow off -- cosmos gas estimation is known to be inaccurate, and we had to bump gas multiplier to account for it. hopefully this should be rare, but at least this will stop the place order to go through when transfer fails during isolated market order
=> fix: parse out of gas error

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRoutePayloadProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/utils/Constants.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt, v4_abacus.podspec
We used to get gas values for the transfer route with Squid and pass them along to the wallet.  But with Skip we no longer get them.   It's better to set them to null for the wallet to figure out the values.
=> Set route gasPrice and gasLimit to null

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketsProcessor.kt, src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4MarketsTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/MarketsChannelMock.kt, v4_abacus.podspec
This is to support user submitted new permissionless market.
=> Add parsing logic for new markets in v4_markets channel update.

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/ReceiptCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/AccountTransformerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountTransformerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TransferInputCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/input/ReceiptLine.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/configs/RewardsParamsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/HistoricalFundingsProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketsSummaryProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+HistoricalFunding.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt, v4_abacus.podspec
=> Static typing: Historical funding and fixing issues with isolated market orders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/AccountCalculatorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/output/account/SubaccountPosition.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt, v4_abacus.podspec
For grouped subaccount of isolated market, the calculated fields for the subaccount have to be moved to the position level.
=> Static Typing: Fix isolated market position calculation

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TriggerOrdersInputProcessor.kt, v4_abacus.podspec
Tested locally and it seems to work.
I can't figure out why this doesn't repro on staging/testnet so might not be the true root cause.
=> fix: trigger order resetting

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/staking/AccountDelegationsProcessor.kt, src/commonMain/kotlin/indexer/models/chain/OnChainDelegationResponse.kt, src/commonTest/kotlin/exchange.dydx.abacus/processor/wallet/account/staking/AccountDelegationsProcessorTests.kt, v4_abacus.podspec
=> fix: staking delegations static typed correctly 

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/OrderbookProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/V4SubaccountsProcessor.kt, v4_abacus.podspec
Need to be careful of ChatGPT generated code :-(
=> Fix subaccount data issue with websocket reconnect

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeOrderInputValidator.kt, v4_abacus.podspec
This error would be triggered whenever postOrderFreeCollateral is larger than your current free collateral.
When you are reducing your position the orderEquity will be negative.
=> fix: Ignore orders that reduce position in equity check

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputMarketOrderCalculator.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/app/adaptors/V4TransactionErrors.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt, v4_abacus.podspec
Also adding tracking code to log client-side exceptions like this.
=> Fix exception when closing a position of > 100% margin usage

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/manager/CctpChainTokenInfo.kt, v4_abacus.podspec
The Polygon route in cctp.json has the same value as what Skip returns but different cases.  So the comparison needs to be case-insensitive.
=> Fix Polygon route

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/CandlesProcessor.kt, v4_abacus.podspec
The batch candle update payload is already in ascending order (unlike the the initial candle payload which is in descending order), so we shouldn't do reverse() for updates.  The batch update only contains 1 or 2 items, so adding a sort() just to be safe here.
=> Fix incorrect order of candle sticks

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/validator/TriggerOrdersInputValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeInputDataValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradePositionStateValidator.kt, src/commonMain/kotlin/exchange.dydx.abacus/validator/trade/TradeResctrictedValidator.kt, v4_abacus.podspec
Fix https://linear.app/dydx/issue/BUG2-213/long-name-for-asset-used-in-errors
=> BUG2-213 Use displayable asset ID for token name in validation messages

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/app/helper/TriggerOrderToastGenerator.kt, v4_abacus.podspec
Fix https://linear.app/dydx/issue/BUG2-214/unable-to-add-tpsl-on-mad-market-it-gets-set-as-price-dollar0
=> BUG2-214 Showing backend error for TP/SL orders

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/output/Market.kt, v4_abacus.podspec
It was only available to un-launched markets before.
=> Adding asset marketCaps to launched markets

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt, v4_abacus.podspec
The compliance screening call needs the indexer config URL to work.  So we need to wait for indexerConnected AND sourceAddress to be available.   Also added complianceScreeningAddress so that we don't call make duplicate calls.
=> Fix compliance screen bug

build.gradle.kts, v4_abacus.podspec
Apparently 1.13.x has been used already.
=> Bump version to 1.14.0

build.gradle.kts, src/commonMain/kotlin/exchange.dydx.abacus/AsyncAbacusStateManagerProtocol.kt, src/commonMain/kotlin/exchange.dydx.abacus/AsyncAbacusStateManagerV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/StateManagerAdaptorV2.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/supervisor/AccountScreener.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/supervisor/AccountScreener.kt.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/supervisor/AccountSupervisor.kt, src/commonMain/kotlin/exchange.dydx.abacus/state/supervisor/AccountsSupervisor.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4ForegroundCycleTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4RestrictionsTests.kt, src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt, v4_abacus.podspec
This allows the app to mutate the compliance state only when user connects a new wallet from a non-compliant region on mobile.
Context: https://dydx-team.slack.com/archives/C05K1ACJ8MB/p1748367331584029
Also refactor the compliance logic to separate it out from AccountSupervisor.
=> Add flag to update user compliance status with new wallet connection only
