build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
integration/iOS/Pods/Target Support Files/abacus/abacus-copy-dsyms-input-files.xcfilelist
integration/iOS/Pods/Target Support Files/abacus/abacus-copy-dsyms.sh
kotlin-js-store/yarn.lock
v4_abacus.podspec

Otherwise it won't work with Xcode 15

Kotlin toolchain update

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/MarketProcessor.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4MarketsTests.kt
v4_abacus.podspec

Sparklines from Indexer is latest-to-earliest. Reverse it in Abacus.
Also fixed iOS integration app

Sparkline from Indexer is reversed.

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/output/Account.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/WalletProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/AccountProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/protocols/PublicProtocols.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/modal/TradingStateMachine+Wallet.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/modal/TradingStateMachine.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4AccountTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/V4OnChainMock.kt
v4_abacus.podspec

Add stakingbalances to `account.stakingBalances`. Tested on web

Support staking balance

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/modal/PerpTradingStateMachine+Transactions.kt
v4_abacus.podspec

It's causing conflict with the string version.

Remove Int version of OrderSide

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/output/TransferStatus.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4SquidTests.kt
v4_abacus.podspec

Going to use it on the client to check the status in addition to the check of the last route step.

[TRCL-3254] Features/squid transaction status

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/processor/squid/SquidProcessor.kt
v4_abacus.podspec

Fix incorrect transfer amount display.

Remove commas from the Squid's amount fields

---

src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TriggerOrdersInput.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/TriggerOrdersInputTests.kt

Depending on whether the user last typed into:
- TriggerInput
- UsdcDiff
- PercentDiff
abacus updates the price to show. Tested via tests in abacus + frontend local branch

Add calculation for price into TriggerOrdersInputCalculator

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/validator/TriggerOrdersInputValidator.kt
src/commonTest/kotlin/exchange.dydx.abacus/validation/TriggerOrdersInputValidationTests.kt
v4_abacus.podspec

so that front-end client knows which fields have caused the validation to fail.
Tested on the Android client.

Add input fields to the trigger order validation

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountTransformer.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
src/commonMain/kotlin/exchange.dydx.abacus/utils/AnalyticsUtils.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/TradeInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v3/V3ClosePositionTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt
v4_abacus.podspec

- add `useOptimisticCollateralCheck` feature flag
- if true, use most optimistic execution price
- update tests

Optimistic collat check

---

.github/workflows/ci.yml
build.gradle.kts
detekt-baseline.xml

https://detekt.dev/ 
This PR sets up the Detekt static analysis tool and configures it to run in CI. I've generated a baseline so any existing issues will be ignored. Detekt is configured to run in type-resolution mode: https://detekt.dev/docs/gettingstarted/type-resolution/ which allows it to run more advanced static analysis checks.
You can run Detekt locally via `./gradlew detektMetadataMain`

Setup Detekt and generate baseline.

---

README.md

we no longer need to manually run publish; also the link to the library was outdated

Remove outdated publish instructions from README

---

build.gradle.kts
v4_abacus.podspec

Forgot to bump in https://github.com/dydxprotocol/v4-abacus/commit/f874b507d1f0ab19734488c396ba174c71f8ac54. sorry :( should add the bump to my alias for making a pr in abacus rip

Bump version

---

detekt.yml

Those two rules should be under "style".

Fix rule configs

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/protocols/LocalizerProtocol.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/app/helper/TriggerOrderToastGenerator.kt
v4_abacus.podspec

Otherwise, the iOS code won't see the function as implemented.

Make LocalizerProtocol.localizeWithParams an extension

---

src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt
src/commonTest/kotlin/exchange.dydx.abacus/app/manager/V4TransactionTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt

28 -> 90 days, per context in linear task

Update sltp order expiration dates

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
v4_abacus.podspec

We are quite a few releases behind: https://github.com/JetBrains/kotlin/releases

chore: Upgrade Kotlin to 1.9.24

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManager.kt
v4_abacus.podspec

Add client logger overwrite to statemanager v1

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/di/AbacusComponent.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt
v4_abacus.podspec

https://github.com/evant/kotlin-inject
Sets up a simple component and provides a function to create the component and access the V2 state manager from it.

Setup kotlin-inject

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt
v4_abacus.podspec

On mobile, we should link the user's Mintscan dydx address page.

Add mintscanBase to env links

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
v4_abacus.podspec

Env json data wasn't parsed correctly.   Tested on Android for both v1 and v2.

Fix mobile force update

---

src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt

Utilize Trade input to determine the `amountToTransfer` for isolated margin trade

Utilize usdcSize Input instead of orderPayload price * size

---

build.gradle.kts
v4_abacus.podspec

notably will incorporate:
- https://github.com/dydxprotocol/v4-abacus/pull/382
- https://github.com/dydxprotocol/v4-abacus/pull/377
- https://github.com/dydxprotocol/v4-abacus/pull/384
- https://github.com/dydxprotocol/v4-abacus/pull/381

bump version of abacus to unblock previous prs

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+TransferInput.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt

as part of the typed state refactor there's a couple of places we aren't setting the new state, quick forward fix

fix: setting tokens chains and resources

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManager.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt
v4_abacus.podspec

feat: cosmos wallet connected

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/V4StateManagerAdaptor.kt
v4_abacus.podspec

missed adding the codebase to the error the older version

fix: adding missing codebase

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountTransformer.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/TradeInputCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/StateManagerAdaptor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+ClosePositionInput.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/EnvironmentsMock.kt
v4_abacus.podspec

`reduceOnlySupported` and `useOptimisticCollateralCheck` are set to true for all envs, therefore can be cleaned up

clean up feature flags: reduce only / collateral checks

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/AdjustIsolatedMarginInputCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+AdjustIsolatedMarginInput.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/AdjustIsolatedMarginInputTests.kt

- `freeCollateral` was used incorrectly, corrected to `margin`

AdjustIsolatedMargin: Fix margin display to equity

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountTransformer.kt

Update `Position Margin` delta to use the exact market order cost

Display correct margin diff when creating a Market Order

---

build.gradle.kts
v4_abacus.podspec

Update v4_abacus.podspec file

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Payloads.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt

* `Payloads`
* add `senderAddress`
* `OnboardingSupervisor`
*  Update to include new payload param
* `SubaccountSupervisor`
* Update ot include new payload param

Add senderAddress to transfer payload

---

build.gradle.kts
v4_abacus.podspec

need to manually bump for podspec to get updated

bump to 1.7.91

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt

"I have added the missing parts to disable autosweep for Keplr wallet connection in StateManagerV2."
Internal copy of https://github.com/dydxprotocol/v4-abacus/pull/440
Related PR: https://github.com/dydxprotocol/v4-abacus/pull/383

fix: dont retrieve noble balance if using cosmos wallet

---

build.gradle.kts
docs/Account.md

As requested by @moo-onthelawn

chore: simple docs about trading rewards objects

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/AccountCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/output/Account.kt
src/commonTest/kotlin/exchange.dydx.abacus/app/helper/TriggerOrderToastGeneratorTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4ParentSubaccountTests.kt

We use this to display the margin for each position.  Currently we do this calculation at client, so let's move it to Abacus.

Add marginValue to SubaccountPosition

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt

* `MarginCalculator`
* add a conditional to ensure that the childSubaccount with no positions or orders also has no equity

ChildSubaccount w/ no positions/orders should also have 0 equity

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt

reduce position -> fully closed position

isolated: fix transfer out condition

---

.github/workflows/bump_version.yml
build.gradle.kts
v4_abacus.podspec

updates podspec version number in github action

add step to github bump version action to bump podspec version

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/SubaccountCalculator.kt
v4_abacus.podspec

Cleanup liquidation price calculation to be easier to read.

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/utils/String+Utils.kt
v4_abacus.podspec

enable smart relay for cctp deposits.

fix: skip deposit smart relay

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/utils/Settings.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/PerpTradingStateMachine.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/BaseTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4BaseTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/state/model/TradingStateMachineTests.kt
v4_abacus.podspec

adds mutable StatsigConfig global object to abacus codebase.
this allows us to update the abacus behavior after its construction on app startup but before we set `readyToConnect` to true

feat: statsig configs

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/SubaccountSupervisor.kt
v4_abacus.podspec

- Update to use new endpoint when useGroupedSubaccounts is enabled

Update historical-pnl endpoint for Grouped Subaccounts

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/MarginCalculator.kt
v4_abacus.podspec

total respects the sign, size doesn't :(

isolated estimate remaining collateral after close position fix: use total instead of size*price

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
v4_abacus.podspec

duplicate https://github.com/dydxprotocol/v4-abacus/pull/474 to pass the bump CI

fix: cancel nobleBalancesTimer when cosmosWalletConnected is true

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Enviroment.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt
v4_abacus.podspec

it's enabled everywhere now (unused)

chore: remove issltp enabled from abacus

---

build.gradle.kts
v4_abacus.podspec

[help](https://app.bitrise.io/build/d516c0aa-c20c-4255-83d2-79f3a70b9145)

bump version to make main work

---

build.gradle.kts
gradle.properties
v4_abacus.podspec

Reference: https://slack-chats.kotlinlang.org/t/16011917/hi-guys-our-multiplatform-ios-app-freezes-when-run-from-xcod

Revert to old GC behavior to fix iOS performance issue.

---

build.gradle.kts
v4_abacus.podspec

just bumping version because my [previous PR](https://github.com/dydxprotocol/v4-abacus/commit/1585144dc42864630ff159b56efeb44191eed4af) was able to merge despite sharing the same version # as [rui's PR](https://github.com/dydxprotocol/v4-abacus/pull/539)

chore:bump version

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
v4_abacus.podspec

exchange rate, exchange received, and gas fee are not available from Skip, so i have conditionally removed
| Before | After |
| ------ | ----- |
| <img src="https://github.com/user-attachments/assets/f5ed3d98-7bea-439a-a2c6-0c4eb43abe65" width="70%" /> | <img src="https://github.com/user-attachments/assets/31b3f971-82c2-4463-936d-fd5a11f83456" width="70%" /> |

remove transfer receipt lines which have unavailable data

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt
src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipRouteProcessorTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/SkipRouteMock.kt
v4_abacus.podspec

Followed up by https://github.com/dydxprotocol/v4-web/pull/907/files
Leverages the `StatsigConfig` to enable configurable max fees
@prashanDYDX dont worry i didn't forget about our convo, here's the ticket to invert this pattern in general https://linear.app/dydx/issue/OTE-723/[investigate]-invert-statsigconfig-pattern

feat: configurable max fee [OTE-722]

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt
v4_abacus.podspec

feat: re-enable usdt [OTE-724]

---

.github/workflows/bump_version.yml
.github/workflows/bump_version_on_main.yml
v4_abacus.podspec

didn't work :( will need to test more on a testing branch

Revert bump version changes

---

src/commonMain/kotlin/exchange.dydx.abacus/calculator/TriggerOrdersInputCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/AccountCalculatorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/AdjustIsolatedMarginInputCalculatorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/output/account/Subaccount.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/input/AdjustIsolatedMarginInputProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/wallet/account/OrdersProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/notification/providers/BlockRewardNotificationProvider.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/notification/providers/OrderStatusChangesNotificationProvider.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/notification/providers/PositionsNotificationProvider.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Account.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/AdjustIsolatedMarginInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/TriggerOrdersInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4AccountOrdersSortingTest.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4AccountTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4CalculationTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4DuplicateWebsocketMessageTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4ParentSubaccountTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4SubaccountTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/processor/wallet/account/OrdersProcessorTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tickets/TRCL2998Tests.kt
src/commonTest/kotlin/exchange.dydx.abacus/validation/TriggerOrdersInputValidationTests.kt

Updating all remaining tests other than those for transfers
Updating PositionsNotificationProvider for static typing
Fixing a trigger order calculation bug with the old codepath (see comment below)

Static Typing: Updating existing tests and bug fixes (2/n)

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/OrderbookCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/markets/OrderbookProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Markets.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Orderbook.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Rewards.kt
src/commonMain/kotlin/exchange.dydx.abacus/utils/Rounder.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/IsolatedMarginModeTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v3/V3MarketsDelayedTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v3/V3OrderbookLoadTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v3/V3OrderbookTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4OrderbookTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4TradeInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/utils/RounderTests.kt
v4_abacus.podspec

- Removing duplicated codepaths.
- Simplifying rounding function. It only applies to the new codepath to minimize the impact.
- Updating orderbook related tests.
- Tested on Android.

Static Typing: Orderbook fixes/optimizations

---

src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/payloads/AbacusMockData.kt

for the FAQ hyperlink on the vault screens. e.g. [here](https://www.figma.com/design/mKevZOfE9nj6MZpiolKYW1/dYdX-%E2%80%BA-Mobile?node-id=9752-5059&t=LU6p7TOHNgckGdhT-4)
corresponding [web PR](https://github.com/dydxprotocol/v4-web/pull/993)

add vaultLearnMore link

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/utils/Logger.kt
v4_abacus.podspec

allows v4-web to serialize/deserialize object to a format that can actually be digested by datadog

fix: send json object instead of map

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessorTests.kt
v4_abacus.podspec

clean up evm swaps ff since we've confirmed it's stable

chore: remove evm swaps ff [OTE-801]

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/AsyncAbacusStateManagerProtocol.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/WalletConnectionType.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/AsyncAbacusStateManagerV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
v4_abacus.podspec

This allows us to branch logic in abacus based on the wallet connection type.

Introduce wallet connection type enum

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountTransformerV2.kt
v4_abacus.podspec

The position list was not updated when a new position is created.  It's because that the calculated size not available when position filter is applied.

CLI-677 Fix issue with position list when static typing is turned on

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/output/Vault.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/vault/VaultProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/configs/V4StateManagerConfigs.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Vault.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/VaultSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4VaultTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/extensions/TradingStateMachine+TestUtils.kt
v4_abacus.podspec

Also removing the stubbed data and wiring-up with the correct indexer url path.

CLI-679 Indexer transfer history

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/VaultDepositWithdrawForm.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/VaultSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultFormTests.kt
v4_abacus.podspec

also updates vault update frequency to 20s

fix need slippage ack condition

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/Environment.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/ConnectionsSupervisor.kt
v4_abacus.podspec

timestamp nonce can be enabled -- will use a statsig flag for safety / ez turn on off

pass in ff_enable_timestamp_nonce flag for validator config

---

build.gradle.kts
src/commonMain/kotlin/indexer/models/chain/OnChainTransactionResponse.kt
v4_abacus.podspec

Add actualWithdrawalAmount property to vault withdraw response

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/output/TransferStatus.kt
v4_abacus.podspec

The data field name might have changed with Skip migration, and it's causing issue with mobile app not showing the up-to-date transfer status.

Fix mobile app transfer status issue

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/functional/vault/Vault.kt
src/commonMain/kotlin/exchange.dydx.abacus/processor/vault/VaultProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine+Vault.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/VaultSupervisor.kt
src/commonTest/kotlin/exchange.dydx.abacus/functional/vault/VaultTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/tests/extensions/TradingStateMachine+TestUtils.kt
v4_abacus.podspec

web merges hourly and daily data into their graph for better near-term granularity. This does the same.

combined hourly and daily data

---

build.gradle.kts
integration/iOS/Pods/Pods.xcodeproj/project.pbxproj
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
v4_abacus.podspec

The transfer chains/tokens still need to be available to the client regardless of the wallet status.

Fix a bug where TransferInput is not updated when user doesn't have a connected wallet

---

src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/SubaccountCalculatorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/TransferInputTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/payload/v4/V4CalculationTests.kt

Currently it's still 0.05 (20x) but BTC and ETH are now at 50x.

Update account level default IMF to 0.02

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/calculator/V2/TradeInput/TradeInputMarketOrderCalculator.kt
src/commonMain/kotlin/exchange.dydx.abacus/output/input/Input.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt
src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4ForegroundCycleTests.kt
src/commonTest/kotlin/exchange.dydx.abacus/app/manager/v2/V4TransactionTests.kt
v4_abacus.podspec

Use childSubaccountErrors for trade/close-position on isolated positions.
Also updating staticTyping for tests.

Fix isolated position withdrawal issue when there is no equity

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipProcessor.kt
v4_abacus.podspec

It doesn't cause issue on mainnet since Skip always returns Eth chain ("1"), but it's not always the case for testnet.

Properly filter the chains before getting the default chain ID

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/output/Configs.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/internalstate/InternalState.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/manager/RpcInfo.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/model/TradingStateMachine.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
v4_abacus.podspec

Client will need the rpc endpoint to query token info.

Expose rpcMap to client

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/processor/input/TransferInputProcessor.kt
v4_abacus.podspec

Otherwise the state might be stale.

Resetting transfer.goFastRoute as needed

---

build.gradle.kts
v4_abacus.podspec

To help DOS with simulator automation

Add iOSX64 flavor

---

build.gradle.kts
v4_abacus.podspec

It causes build issue on Android

Revert last PR

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/manager/StateManagerAdaptorV2.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountsSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/Configs.kt
v4_abacus.podspec

Let the client to optionally disable screening.

Add option to disable screening

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/processor/router/skip/SkipTrackProcessor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/AccountSupervisor.kt
src/commonMain/kotlin/exchange.dydx.abacus/state/v2/supervisor/OnboardingSupervisor.kt
v4_abacus.podspec

Solana tx hashes are case-sensitive, so we shouldn't do lowercase().

Fix Solana deposit status

---

build.gradle.kts
src/commonMain/kotlin/exchange.dydx.abacus/functional/ClientAnalyticEvents.kt
v4_abacus.podspec

so that clients have consistent event params

Add shared events
